# Generated by Django 5.2.8 on 2025-11-13 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Startup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id_invest', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('date', models.DateField()),
                ('commentaire', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='Startup.startup')),
            ],
            options={
                'db_table': 'investissement',
            },
        ),
    ]
