# Generated by Django 5.2.7 on 2025-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de l'événement"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("conference", "Conférence"),
                            ("workshop", "Atelier"),
                            ("concert", "Concert"),
                            ("festival", "Festival"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Prix (en DT)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("date", models.DateField(verbose_name="Date de l'événement")),
                ("location", models.CharField(max_length=200, verbose_name="Lieu")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event_images/",
                        verbose_name="Image de l'événement",
                    ),
                ),
                (
                    "total_seats",
                    models.PositiveIntegerField(verbose_name="Places totales"),
                ),
                (
                    "reserved_seats",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Places réservées"
                    ),
                ),
                (
                    "id_user",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
            ],
        ),
    ]
