# Generated by Django 5.2.7 on 2025-11-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventApp", "0002_remove_event_image_event_photo_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="event",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
    ]
