# Generated by Django 5.2.7 on 2025-11-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventApp", "0003_remove_event_photo_url_event_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="photo",
        ),
        migrations.AddField(
            model_name="event",
            name="photo_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Photo (URL)"
            ),
        ),
    ]
