# Generated by Django 5.2.7 on 2025-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventApp", "0004_remove_event_photo_event_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="photo_url",
            field=models.URLField(blank=True, null=True, verbose_name="Photo (URL)"),
        ),
    ]
