# Generated by Django 5.2.7 on 2025-11-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventApp", "0005_alter_event_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="price",
            field=models.FloatField(verbose_name="Prix (en DT)"),
        ),
    ]
