# Generated by Django 5.2.7 on 2025-11-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventApp", "0006_alter_event_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="photo_url",
            field=models.CharField(
                blank=True,
                max_length=10000,
                null=True,
                verbose_name="Photo (URL ou Data URI)",
            ),
        ),
    ]
