# Generated by Django 5.2.7 on 2025-11-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventApp", "0008_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="id_user",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
