# Generated by Django 5.2.7 on 2025-11-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0009_seat_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='names',
        ),
    ]
