# Generated by Django 5.2.7 on 2025-11-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventApp", "0009_seat_id_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
