# Generated by Django 5.2.7 on 2025-11-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0010_rename_name_event_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='names',
            new_name='name',
        ),
    ]
