# Generated by Django 5.2.8 on 2025-11-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventApp", "0011_rename_names_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
