# Generated by Django 5.2.7 on 2025-11-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulation', '0003_postulation_statut_alter_postulation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id_entretien', models.AutoField(primary_key=True, serialize=False)),
                ('date_entretien', models.DateTimeField(verbose_name="Date et heure de l'entretien")),
                ('lien_meet', models.CharField(blank=True, help_text='Lien Zoom, Teams, Google Meet, etc.', max_length=500, null=True, verbose_name='Lien de visioconférence')),
                ('commentaire', models.TextField(blank=True, help_text="Notes ou commentaires sur l'entretien", null=True, verbose_name='Commentaire')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('effectue', 'Effectué'), ('annule', 'Annulé')], default='planifie', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('postulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entretien', to='postulation.postulation', verbose_name='Postulation')),
            ],
            options={
                'verbose_name': 'Entretien',
                'verbose_name_plural': 'Entretiens',
                'ordering': ['-date_entretien'],
            },
        ),
    ]
