# Generated by Django 5.2.7 on 2025-11-07 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovoiturageApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='lieu_arrivee',
            new_name='depart',
        ),
        migrations.RenameField(
            model_name='offre',
            old_name='lieu_depart',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='heure_depart',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='nb_places',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='statut',
        ),
        migrations.AddField(
            model_name='offre',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offre',
            name='conducteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
