# Generated by Django 5.2.7 on 2025-11-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovoiturageApp', '0002_rename_lieu_arrivee_offre_depart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='nombre_places',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offre',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
