# Generated by Django 5.2.7 on 2025-11-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovoiturageApp', '0003_offre_nombre_places_offre_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='date_covoiturage',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
