# Generated by Django 5.2.7 on 2025-11-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovoiturageApp', '0004_offre_date_covoiturage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='climatisation',
            field=models.BooleanField(default=False, verbose_name='Climatisation'),
        ),
        migrations.AddField(
            model_name='offre',
            name='modele_voiture',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modèle de voiture'),
        ),
    ]
