# Generated by Django 5.2.8 on 2025-11-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovoiturageApp', '0006_alter_offre_conducteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='preference_genre',
            field=models.CharField(choices=[('tous', 'Tous'), ('homme', 'Hommes uniquement'), ('femme', 'Femmes uniquement')], default='tous', max_length=10, verbose_name='Préférence de genre'),
        ),
    ]
