# Generated by Django 5.2.8 on 2025-11-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovoiturageApp', '0007_offre_preference_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='approuve',
            field=models.BooleanField(default=False, help_text="L'offre doit être approuvée par l'administrateur avant d'être visible publiquement", verbose_name='Approuvé'),
        ),
    ]
