# Generated by Django 5.2.7 on 2025-12-19 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovoiturageApp', '0009_alter_offre_conducteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='comfort_score',
            field=models.IntegerField(default=50, help_text='Score de confort global (0-100): climatisation, sièges, propreté, musique, etc.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de Confort'),
        ),
    ]
