# Generated by Django 5.2.7 on 2025-12-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovoiturageApp', '0010_offre_comfort_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='comfort_score',
        ),
        migrations.AddField(
            model_name='offre',
            name='confort_percent',
            field=models.IntegerField(default=50, help_text='Niveau de confort du véhicule/trajet (0-100)', verbose_name='Pourcentage de confort'),
        ),
    ]
