# Generated by Django 5.2.7 on 2025-11-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='face_id_enabled',
            field=models.BooleanField(default=False, verbose_name='Face ID activÃ©'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='face_id_public_key',
            field=models.TextField(blank=True, null=True, verbose_name='ClÃ© publique Face ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Email vÃ©rifiÃ©'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='DerniÃ¨re connexion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TÃ©lÃ©phone'),
        ),
    ]
