# Generated by Django 5.2.7 on 2025-11-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_customuser_bio_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Photo de couverture'),
        ),
    ]
