# Generated by Django 5.2.7 on 2025-11-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_message_deleted_message_file_message_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_connection_request',
            field=models.BooleanField(default=False, verbose_name='Message de demande de connexion'),
        ),
    ]
