# Generated by Django 5.2.7 on 2025-11-12 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogementApp', '0004_logement_rejected'),
        ('UserApp', '0009_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='logement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='LogementApp.logement', verbose_name='Logement (Marketplace)'),
        ),
    ]
