# Generated by Django 5.2.7 on 2025-12-02 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_make_phone_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu du message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
            ],
            options={
                'verbose_name': 'Message Admin',
                'verbose_name_plural': 'Messages Admin',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like_per_user_per_post',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user')},
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='admin_messages_read', to=settings.AUTH_USER_MODEL, verbose_name='Lu par'),
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
    ]
