# Generated by Django 5.2.8 on 2025-11-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0012_make_phone_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="like",
            name="unique_like_per_user_per_post",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("post", "user")},
        ),
    ]
