# Generated by Django 5.2.7 on 2025-12-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_adminmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='edubox_audio/', verbose_name='Fichier audio'),
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Modifié'),
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de modification'),
        ),
    ]
