# Generated by Django 5.2.7 on 2025-12-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_adminmessage_audio_file_adminmessage_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='edubox_files/', verbose_name='Fichier'),
        ),
    ]
