# Generated by Django 5.2.7 on 2025-12-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='posts/media/', verbose_name='Média (vidéo)'),
        ),
    ]
