# Generated by Django 5.2.8 on 2025-11-13 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id_startup', models.AutoField(primary_key=True, serialize=False)),
                ('nom_startup', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
                ('description', models.TextField()),
                ('fond_desire', models.FloatField()),
                ('fond_actuel', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('funded', 'Funded'), ('failed', 'Failed'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Startup',
            },
        ),
    ]
