# Generated by Django 5.2.8 on 2025-11-13 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Startup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupMember',
            fields=[
                ('id_member', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='Member', max_length=100)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Startup.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'startup')},
            },
        ),
    ]
