# Generated by Django 5.2.8 on 2025-11-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StartupMembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='startupmember',
            table='startup_member',
        ),
    ]
