# Generated by Django 5.2.7 on 2025-11-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id_offre', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('inscription', models.DateField()),
                ('domaine', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('remuneration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(max_length=50)),
                ('duree', models.IntegerField(help_text='Durée en semaines ou en mois')),
                ('visibilite', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offres_images/')),
            ],
        ),
    ]
