# Generated by Django 5.2.7 on 2025-11-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offreStage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offrestage',
            name='inscription',
        ),
        migrations.AddField(
            model_name='offrestage',
            name='description',
            field=models.TextField(default='Description temporaire'),
            preserve_default=False,
        ),
    ]
