# Generated by Django 5.2.7 on 2025-11-07 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offreStage', '0002_remove_offrestage_inscription_offrestage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offrestage',
            name='date_publication',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de publication'),
        ),
    ]
