# Generated by Django 5.2.7 on 2025-11-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offreStage', '0003_offrestage_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offrestage',
            name='etat',
            field=models.CharField(default='disponible', max_length=50),
        ),
    ]
