# Generated by Django 5.2.7 on 2025-11-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offreStage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id_postulation', models.AutoField(primary_key=True, serialize=False)),
                ('date_postulation', models.DateField(auto_now_add=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('lettre_motivation', models.TextField()),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulations', to='offreStage.offrestage')),
            ],
        ),
    ]
