# Generated by Django 5.2.7 on 2025-11-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulation',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
    ]
