# Generated by Django 5.2.7 on 2025-11-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulation', '0002_postulation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
