# Generated by Django 5.2.7 on 2025-11-12 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_logement', models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('MAISON', 'Maison'), ('STUDIO', 'Studio'), ('VILLA', 'Villa'), ('AUTRE', 'Autre')], default='APPARTEMENT', max_length=20, verbose_name='Type de logement')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Surface (m²)')),
                ('rooms', models.IntegerField(verbose_name='Nombre de pièces')),
                ('bathrooms', models.IntegerField(default=1, verbose_name='Nombre de salles de bain')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logements/', verbose_name='Image')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logements', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Logement',
                'verbose_name_plural': 'Logements',
                'ordering': ['-created_at'],
            },
        ),
    ]
