# Generated by Django 5.2.7 on 2025-11-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
    ]
