# Generated by Django 5.2.7 on 2025-11-12 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogementApp', '0004_logement_rejected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BinomeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la recherche')),
                ('description', models.TextField(help_text='Décrivez ce que vous cherchez (budget, préférences, etc.)', verbose_name='Description')),
                ('city', models.CharField(max_length=100, verbose_name='Ville recherchée')),
                ('budget_max', models.DecimalField(decimal_places=2, help_text='Budget maximum par mois', max_digits=10, verbose_name='Budget maximum (DT)')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Rejeté'), ('COMPLETED', 'Complété')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('logement', models.ForeignKey(blank=True, help_text='Logement spécifique (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binome_requests', to='LogementApp.logement', verbose_name='Logement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binome_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Demande de binôme',
                'verbose_name_plural': 'Demandes de binômes',
                'ordering': ['-created_at'],
            },
        ),
    ]
