# Generated by Django 5.2.7 on 2025-12-18 19:01

import LogementApp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogementApp', '0008_update_video_field_upload_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='video',
            field=models.FileField(blank=True, help_text='Fichier vidéo (MP4, WebM, OGG, etc.)', null=True, upload_to=LogementApp.models.video_upload_to, verbose_name='Vidéo (fichier optionnel)'),
        ),
        migrations.CreateModel(
            name='TemporaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logements/temp/', verbose_name='Image temporaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_images', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Image temporaire',
                'verbose_name_plural': 'Images temporaires',
                'ordering': ['-created_at'],
            },
        ),
    ]
