# Generated by Django 5.2.7 on 2025-11-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nombre_places_reservees',
            field=models.IntegerField(default=1, verbose_name='Nombre de places réservées'),
        ),
    ]
