# Generated by Django 5.2.7 on 2025-11-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nom_passager',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du passager'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='telephone_passager',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du passager'),
        ),
    ]
