# Generated by Django 5.2.7 on 2025-11-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0004_reservation_nom_passager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='nom_passager',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nombre_places_reservees',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée par le passager')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='telephone_passager',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
